### ISSUE TITLE
Failed to use consul as autocluster provider in a k8s environment

### ISSUE THREAD

**Issue by cambierr** [rabbitmq/rabbitmq-peer-discovery-consul#22]
Hi,

When trying to use consul as autocluster provider, I'm always receiving the same error message from rabbit: `{badrpc,nodedown}`.

Here is my consul config:
```yml
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  selector:
    app: consul
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: "consul:latest"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "agent"
        - "-advertise=$(POD_IP)"
        - "-bind=0.0.0.0"
        - "-bootstrap-expect=2"
        - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
        - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
        - "-client=0.0.0.0"
        - "-datacenter=$(NAMESPACE)"
        - "-domain=cluster.local"
        - "-server"
        - "-ui"
        ports:
        - containerPort: 8500
          name: ui-port

---
```
and the rabbitmq config:
```yml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: http
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "rabbitmq:3.7.8-management"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_ERLANG_COOKIE
          value: "RDYZGGYQNZDSJOKEWCPP"
        - name: RABBITMQ_DEFAULT_USER
          value: "tucano"
        - name: RABBITMQ_DEFAULT_PASS
          value: "tucano"
        command: ["/bin/bash", "-c"]
        args: ["apt-get update && apt-get install -y tcpdump && { tcpdump -i eth0 >> /tmp/capture & } && echo '[rabbitmq_management,rabbitmq_peer_discovery_consul].' > /etc/rabbitmq/enabled_plugins && printf 'cluster_formation.peer_discovery_backend = rabbit_peer_discovery_consul\ncluster_formation.consul.host = $(POD_IP)\ncluster_formation.consul.svc_addr_auto = false\ncluster_formation.consul.svc_addr = $(HOSTNAME).rabbitmq.$(NAMESPACE).svc.cluster.local\ncluster_formation.consul.use_longname = true\nlog.file.level = debug\nlog.console.level = debug\n' > /etc/rabbitmq/rabbitmq.conf && docker-entrypoint.sh rabbitmq-server"]
        ports:
        - containerPort: 15672
          name: http
      - name: consul
        image: "consul:latest"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONSUL_LOCAL_CONFIG
          value: '{"leave_on_terminate": true}'
        args:
        - "agent"
        - "-advertise=$(POD_IP)"
        - "-bind=0.0.0.0"
        - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
        - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
        - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
        - "-client=0.0.0.0"
        - "-datacenter=$(NAMESPACE)"
        - "-disable-host-node-id"
        ports:
        - containerPort: 5672
          name: ui-port
        - containerPort: 5672
          name: alt-port
        - containerPort: 53
          name: udp-port
        - containerPort: 8443
          name: https-port
        - containerPort: 8080
          name: http-port
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8600
          name: consuldns
        - containerPort: 8300
          name: server
```

As you can see, nothing strange here.

When starting the rabbitmq part ( a while after consul to make sure consul is ok), the first rabbit pods starts according to plan. The second always fails with the `{badrpc,nodedown}` error.

From what I see in a tcpdump:
```text
root@rabbitmq-1:/# cat /tmp/capture-since-start | grep rabbitmq-0
16:26:13.650327 IP kube-dns.kube-system.svc.cluster.local.53 > rabbitmq-1.rabbitmq.default.svc.cluster.local.40438: 62515 1/0/0 PTR rabbitmq-0.rabbitmq.default.svc.cluster.local. (100)
16:26:27.479555 IP rabbitmq-1.rabbitmq.default.svc.cluster.local.48116 > kube-dns.kube-system.svc.cluster.local.53: 33608+ A? rabbitmq-0.default.svc.cluster.local. (54)
16:26:27.480941 IP rabbitmq-1.rabbitmq.default.svc.cluster.local.33927 > kube-dns.kube-system.svc.cluster.local.53: 20145+ A? rabbitmq-0.svc.cluster.local. (46)
16:26:27.482527 IP rabbitmq-1.rabbitmq.default.svc.cluster.local.50758 > kube-dns.kube-system.svc.cluster.local.53: 59022+ A? rabbitmq-0.cluster.local. (42)
16:26:27.483491 IP rabbitmq-1.rabbitmq.default.svc.cluster.local.37612 > kube-dns.kube-system.svc.cluster.local.53: 32724+ A? rabbitmq-0. (28)
```
```text
root@rabbitmq-1:/# cat /tmp/capture-since-start | grep "10.25.2.62"  # this is the rabbitmq-0 internal ip address
<nothing>
```
At this point, I'm not sure to know what to do and you help would be highly appreciated !
